apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-dops
  namespace: argocd
spec:
  project: dops
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: git@github.com:jmcc-sss/argocd-testing.git
    targetRevision: main
    path: argocd/dops/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
