# REQUIRED: to tell the appset which cluster to deploy this to
name: argo-staging
# REQUIRED: to tell the appset which namespace to deploy this to
namespace: beacon
# REQUIRED: to tell the appset which environment to deploy this to
environment: staging
