# REQUIRED: to tell the appset which cluster to deploy this to
name: argo-staging
# REQUIRED: to tell the appset which namespace to deploy this to
namespace: beacon
environment: staging
clusterUrl: https://192.168.1.85:6445

# REQUIRED: helps build the argocd application name
appName: baseline

sources: 
- type: raw
  rawRepoURL: git@github.com:jmcc-sss/argocd-testing.git
  rawTargetRevision: main
  rawPath: beacon/staging/beacon/baseline
# - type: helm
#   helmRepoURL: https://github.com/your-org/my-app.git
#   helmTargetRevision: main
#   helmValueFiles:
#     - values.yaml
#     - values-prod.yaml
# - type: git
#   gitRepoURL: git@github.com:jmcc-sss/argocd-testing.git
#   gitTargetRevision: main
#   gitPath: deploy/helm
#   gitRef: values
